# Generated by Django 4.2.9 on 2024-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_date_alter_person_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
